### ISSUE TITLE
读取日历

### ISSUE THREAD

**Issue by xixaxoqiqaqo** [smartmimi/JSBox#1]
- 读取日历
- 在 Input Value 输入日期
- 同时显示春节(小)和当前的日期(大)
- 自动下一个日期

**Comment by smartmimi** [comment]
> * 读取日历
> * 在 Input Value 输入日期
> * 同时显示春节(小)和当前的日期(大)
> * 自动下一个日期

此脚本为练手作品。不准备继续维护。如果要满足日历、input等，需要的工作量较大。
提到的需求，我回复下，方便你自己修改成想要的样子。
关于第三条，显示的样式也纠结了挺多，后来随便选了个看的过去的。可以在view里修改。
关于第四条，现有的App或者脚本，在多个日期之间切换的逻辑，大致为两类
1、每个小组件显示一个。新建多个组件并叠加，看的时候滑动即可翻页（推荐此脚本用这个用法）。
2、按一定顺序自动切换。但是不一定显示到自己想看到那一个时间。
目前采用的是第一种方式。因为iOS14小组件的交互性约等于0.导致想显示太多的话，基本没法实现。

**Comment by xixaxoqiqaqo** [comment]
> > * 读取日历
> > * 在 Input Value 输入日期
> > * 同时显示春节(小)和当前的日期(大)
> > * 自动下一个日期
> 
> 此脚本为练手作品。不准备继续维护。如果要满足日历、input等，需要的工作量较大。
> 提到的需求，我回复下，方便你自己修改成想要的样子。
> 关于第三条，显示的样式也纠结了挺多，后来随便选了个看的过去的。可以在view里修改。
> 关于第四条，现有的App或者脚本，在多个日期之间切换的逻辑，大致为两类
> 1、每个小组件显示一个。新建多个组件并叠加，看的时候滑动即可翻页（推荐此脚本用这个用法）。
> 2、按一定顺序自动切换。但是不一定显示到自己想看到那一个时间。
> 目前采用的是第一种方式。因为iOS14小组件的交互性约等于0.导致想显示太多的话，基本没法实现。

- 我没有学过编程，现在我只会基于抄代码的修代码(以Time时间卡为例我只会增加日期)

**Comment by xixaxoqiqaqo** [comment]
- 样式我想到了显示百分比，像天气的 °

**Comment by xixaxoqiqaqo** [comment]
- 自动切换最近的日期准没错
- iOS 14 小组件不能滑动
